### ISSUE TITLE
Test button won't show in Camunda modeler v4.x

### ISSUE THREAD

**Issue by vincentgiraud** [bpmn-io/dmn-testing-plugin#21]
The test button won't show in Camunda modeler (v4.3 and v4.7.0 tested)

I've dropped the project into resources/plugins of the v4.7.0 Camunda modeler for mac OS (11.2.2).

Open a dmn file, click the overview for a decision table, no test button will show.

**Comment by barmac** [comment]
Did you clone the latest version of the repository? Did you install Java as described in [the usage info](https://github.com/bpmn-io/dmn-testing-plugin#how-to-use)?

**Comment by vincentgiraud** [comment]
I finally got it to work. I didn't put the project in the right place: ~/Library/Application\ Support
